
// AUTO-GENERATED BY m2cgen & Scikit-Learn
// Do not modify manually.

Map<String, int> modelVocabulary = {"massive": 16, "fast": 6, "main": 15, "building": 2, "debris": 3, "need": 18, "help": 8, "immediately": 9, "bleeding": 0, "heavily": 7, "evacuation": 4, "medical": 17, "injuries": 11, "water": 19, "level": 13, "lost": 14, "blocked": 1, "fallen": 5, "just": 12, "incident": 10, "collapse": 20, "leak": 21, "unconscious": 22, "structure": 23};
List<String> classes = ["CRITICAL", "HIGH", "LOW"];

List<double> score(List<double> input) {
    List<double> var0;
    if (input[18] <= 0.20850630104541779) {
        if (input[7] <= 0.3535533845424652) {
            var0 = [0.0, 0.0, 1.0];
        } else {
            var0 = [1.0, 0.0, 0.0];
        }
    } else {
        if (input[18] <= 0.4305717349052429) {
            var0 = [0.0, 1.0, 0.0];
        } else {
            if (input[19] <= 0.2890629768371582) {
                var0 = [0.0, 1.0, 0.0];
            } else {
                var0 = [0.0, 0.0, 1.0];
            }
        }
    }
    List<double> var1;
    if (input[18] <= 0.2721565067768097) {
        if (input[6] <= 0.25) {
            if (input[19] <= 0.3226286470890045) {
                var1 = [0.0, 0.0, 1.0];
            } else {
                var1 = [0.0, 1.0, 0.0];
            }
        } else {
            var1 = [1.0, 0.0, 0.0];
        }
    } else {
        var1 = [0.0, 1.0, 0.0];
    }
    List<double> var2;
    if (input[19] <= 0.6116916239261627) {
        if (input[6] <= 0.25) {
            if (input[19] <= 0.2890629768371582) {
                if (input[1] <= 0.3535533845424652) {
                    if (input[0] <= 0.3535533845424652) {
                        var2 = [0.0, 0.0, 1.0];
                    } else {
                        var2 = [1.0, 0.0, 0.0];
                    }
                } else {
                    var2 = [0.0, 0.0, 1.0];
                }
            } else {
                var2 = [0.0, 0.0, 1.0];
            }
        } else {
            var2 = [1.0, 0.0, 0.0];
        }
    } else {
        var2 = [0.0, 1.0, 0.0];
    }
    List<double> var3;
    if (input[1] <= 0.3535533845424652) {
        if (input[6] <= 0.25) {
            if (input[7] <= 0.3535533845424652) {
                if (input[17] <= 0.32134491205215454) {
                    if (input[13] <= 0.3819826543331146) {
                        var3 = [0.3333333333333333, 0.3333333333333333, 0.3333333333333333];
                    } else {
                        var3 = [0.0, 1.0, 0.0];
                    }
                } else {
                    var3 = [0.0, 1.0, 0.0];
                }
            } else {
                var3 = [1.0, 0.0, 0.0];
            }
        } else {
            var3 = [1.0, 0.0, 0.0];
        }
    } else {
        var3 = [0.0, 0.0, 1.0];
    }
    List<double> var4;
    if (input[4] <= 0.4194411039352417) {
        var4 = [0.0, 0.0, 1.0];
    } else {
        var4 = [0.0, 1.0, 0.0];
    }
    List<double> var5;
    if (input[4] <= 0.4194411039352417) {
        if (input[5] <= 0.3535533845424652) {
            if (input[3] <= 0.27032899856567383) {
                if (input[19] <= 0.2890629768371582) {
                    var5 = [1.0, 0.0, 0.0];
                } else {
                    if (input[14] <= 0.34224191308021545) {
                        var5 = [0.0, 1.0, 0.0];
                    } else {
                        var5 = [0.0, 0.0, 1.0];
                    }
                }
            } else {
                var5 = [1.0, 0.0, 0.0];
            }
        } else {
            var5 = [0.0, 0.0, 1.0];
        }
    } else {
        var5 = [0.0, 1.0, 0.0];
    }
    List<double> var6;
    if (input[13] <= 0.3819826543331146) {
        if (input[8] <= 0.27032899856567383) {
            if (input[18] <= 0.2721565067768097) {
                var6 = [1.0, 0.0, 0.0];
            } else {
                var6 = [0.0, 1.0, 0.0];
            }
        } else {
            var6 = [1.0, 0.0, 0.0];
        }
    } else {
        var6 = [0.0, 1.0, 0.0];
    }
    List<double> var7;
    if (input[0] <= 0.3535533845424652) {
        if (input[15] <= 0.25) {
            if (input[13] <= 0.3819826543331146) {
                if (input[10] <= 0.3535533845424652) {
                    if (input[18] <= 0.4305717349052429) {
                        var7 = [0.0, 1.0, 0.0];
                    } else {
                        var7 = [0.0, 0.5, 0.5];
                    }
                } else {
                    var7 = [0.0, 0.0, 1.0];
                }
            } else {
                var7 = [0.0, 1.0, 0.0];
            }
        } else {
            var7 = [1.0, 0.0, 0.0];
        }
    } else {
        var7 = [1.0, 0.0, 0.0];
    }
    List<double> var8;
    if (input[12] <= 0.3535533845424652) {
        if (input[4] <= 0.4194411039352417) {
            if (input[18] <= 0.20850630104541779) {
                var8 = [1.0, 0.0, 0.0];
            } else {
                if (input[17] <= 0.32134491205215454) {
                    var8 = [0.0, 0.0, 1.0];
                } else {
                    var8 = [0.0, 1.0, 0.0];
                }
            }
        } else {
            var8 = [0.0, 1.0, 0.0];
        }
    } else {
        var8 = [0.0, 0.0, 1.0];
    }
    List<double> var9;
    if (input[15] <= 0.25) {
        if (input[8] <= 0.27032899856567383) {
            var9 = [0.0, 0.0, 1.0];
        } else {
            var9 = [1.0, 0.0, 0.0];
        }
    } else {
        var9 = [1.0, 0.0, 0.0];
    }
    return mulVectorNumber(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(var0, var1), var2), var3), var4), var5), var6), var7), var8), var9), 0.1);
}
List<double> addVectors(List<double> v1, List<double> v2) {
    List<double> result = List<double>.filled(v1.length, 0.0);
    for (int i = 0; i < v1.length; i++) {
        result[i] = v1[i] + v2[i];
    }
    return result;
}
List<double> mulVectorNumber(List<double> v1, double num) {
    List<double> result = List<double>.filled(v1.length, 0.0);
    for (int i = 0; i < v1.length; i++) {
        result[i] = v1[i] * num;
    }
    return result;
}


String scoreDistressText(String text) {
  // 1. Basic Tokenization matching python vectorizer
  var words = text.toLowerCase().replaceAll(RegExp(r'[^a-z0-9\s]'), '').split(' ');
  
  // 2. Vectorize mapping
  List<double> features = List.filled(24, 0.0);
  for (var w in words) {
    if (modelVocabulary.containsKey(w)) {
      // TF-IDF simplified to term presence to avoid complex dart idf math for this example
      features[modelVocabulary[w]!] += 1.0; 
    }
  }
  
  // 3. Score using exported M2CGen tree
  List<double> scores = score(features);
  
  // 4. Return argmax class
  int maxIndex = 0;
  for (int i = 1; i < scores.length; i++) {
    if (scores[i] > scores[maxIndex]) {
      maxIndex = i;
    }
  }
  
  return classes[maxIndex];
}
