import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
import m2cgen as m2c
import json
import os

def train_and_export_model():
    print("Training Scikit-Learn Random Forest on Distress Data...")
    
    # 1. Dataset Generation
    data = [
        ("Massive fire spreading fast in the main building", "CRITICAL"),
        ("Trapped under the debris, need help immediately", "CRITICAL"),
        ("Someone is bleeding heavily here, unconscious", "CRITICAL"),
        ("Building structure collapse multiple casualties", "CRITICAL"),
        ("Gas leak detected in the basement area", "CRITICAL"),
        ("We are stuck but safe for now, need evacuation", "HIGH"),
        ("Need medical supplies for minor injuries", "HIGH"),
        ("Stranded on the roof, water level rising", "HIGH"),
        ("Broken limb, need transport soon", "HIGH"),
        ("Flooded ground floor, moving to higher ground", "HIGH"),
        ("Lost power, need food and water soon", "LOW"),
        ("Road is blocked by fallen trees", "LOW"),
        ("We are okay, just reporting the incident", "LOW"),
        ("Minor property damage but everyone is safe", "LOW"),
        ("Requesting general information about shelter", "LOW")
    ]
    
    df = pd.DataFrame(data, columns=["text", "severity"])
    
    # 2. Vectorization - We use a simple count/TF-IDF limit so the generated Dart code isn't 100MB
    vectorizer = TfidfVectorizer(max_features=20, stop_words='english')
    X = vectorizer.fit_transform(df['text'])
    y = df['severity']
    
    # 3. Model Training
    # Limit depth and estimators heavily so m2cgen doesn't crash dart compiler with massive switch statements
    rf = RandomForestClassifier(n_estimators=10, max_depth=5, random_state=42)
    rf.fit(X, y)
    
    print("Accuracy on training data:", rf.score(X, y))
    
    # 4. Exporting to Dart!
    # m2cgen supports RandomForestClassifier directly.
    try:
        dart_code = m2c.export_to_dart(rf)
        
        # We also need the vocabulary to tokenize the string in Dart. Convert numpy int64 to native int.
        vocab = {k: int(v) for k, v in vectorizer.vocabulary_.items()}
        
        # Format the Dart output
        dart_file_content = f"""
// AUTO-GENERATED BY m2cgen & Scikit-Learn
// Do not modify manually.

Map<String, int> modelVocabulary = {json.dumps(vocab)};
List<String> classes = {json.dumps(list(rf.classes_))};

{dart_code}

String scoreDistressText(String text) {{
  // 1. Basic Tokenization matching python vectorizer
  var words = text.toLowerCase().replaceAll(RegExp(r'[^a-z0-9\\s]'), '').split(' ');
  
  // 2. Vectorize mapping
  List<double> features = List.filled({len(vocab)}, 0.0);
  for (var w in words) {{
    if (modelVocabulary.containsKey(w)) {{
      // TF-IDF simplified to term presence to avoid complex dart idf math for this example
      features[modelVocabulary[w]!] += 1.0; 
    }}
  }}
  
  // 3. Score using exported M2CGen tree
  List<double> scores = score(features);
  
  // 4. Return argmax class
  int maxIndex = 0;
  for (int i = 1; i < scores.length; i++) {{
    if (scores[i] > scores[maxIndex]) {{
      maxIndex = i;
    }}
  }}
  
  return classes[maxIndex];
}}
"""
        
        output_path = os.path.join(os.path.dirname(__file__), '../resqnet/lib/services/ml_model.dart')
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(dart_file_content)
        
        print(f"Successfully generated Dart ML code at {output_path}")
    except Exception as e:
        print(f"Failed to generate dart code: {e}")

if __name__ == '__main__':
    train_and_export_model()
